[dbProperties]
username = "postgres"
password = "123"
database = "postgres"

[serverRun]
port = "8080"

[mailProperties]
from = "correo@gmail.com"
password = "121345677"
hostname = "smtp.gmail.com:587"
servername = "smtp.gmail.com"
